### ISSUE TITLE
Can't copy file to destination folder

### ISSUE THREAD

**Issue by sheltondong** [rollup/rollup-plugin-url#13]
I am using this config:
```javascript
url({
    limit: 1024 * 100,
    include: ['.png', '.jpg'],
})
```
And I have this css file:
```css
.test {
    background-image: url('javascript_logo.png');
}
```
But it doesn't copy the image file to the destination folder.
